version: "3.9"

services:
  reportes-tabantaj:
    build: .
    container_name: reportes-tabantaj
    restart: unless-stopped
    tty: true
    ports:
      - "3300:3300"
    command: "./goservices"
    volumes:
      - .:/goservices
    networks:
      - tabantajnetwork

networks:
  tabantajnetwork:
